package tongcheng

// 58.com 属性与 p2hr 对应关系

// CategoryMate 58同城职位分类匹配关系
var CategoryMate = map[string]string{
	//生活 | 服务业
	"zplvyoujiudian餐饮":    "酒店/餐饮类",
	"cantfwy服务员":          "酒店/餐饮类",
	"songcanyuan送餐员":      "酒店/餐饮类",
	"canguan厨师/厨师长":       "酒店/餐饮类",
	"houchuczg后厨":         "酒店/餐饮类",
	"chuancaiyuan传菜员":     "酒店/餐饮类",
	"chufangqiepei配菜/打荷":  "酒店/餐饮类",
	"xiwangong洗碗工":        "酒店/餐饮类",
	"miandianshi面点师":      "酒店/餐饮类",
	"chayi茶艺师":            "酒店/餐饮类",
	"qiantjd迎宾/接待":        "酒店/餐饮类",
	"datangjingli大堂经理/领班": "酒店/餐饮类",
	"jiudianjl餐饮管理":       "酒店/餐饮类",
	"zpxuetu学徒":           "酒店/餐饮类",
	"zpzagong杂工":          "酒店/餐饮类",
	"zpkafei咖啡师":          "酒店/餐饮类",
	"zpyudingyuan预订员":     "酒店/餐饮类",

	"jiazhengbaojiexin家政保洁/安保": "公众服务类",
	"baojieyuan保洁":             "公众服务类",
	"baomuxin保姆":               "公众服务类",
	"yuesaoyuying月嫂":           "公众服务类",
	"yuying育婴师/保育员":            "公众服务类",
	"xiyifang洗衣工":              "公众服务类",
	"zhdiang钟点工":               "公众服务类",
	"baoanl保安":                 "公众服务类",
	"hugong护工":                 "公众服务类",
	"songshuigong送水工":          "公众服务类",

	"meirongjianshen美容/美发": "公众服务类",
	"faxingshi发型师":         "公众服务类",
	"meifaxuetu美发助理/学徒":    "公众服务类",
	"xitougong洗头工":         "公众服务类",
	"zpmeirongdaoshi美容导师":  "公众服务类",
	"meirongshi美容师":        "公众服务类",
	"meirongzhuli美容助理/学徒":  "公众服务类",
	"huazhuangshizg化妆师":    "公众服务类",
	"meitishi美甲师":          "公众服务类",
	"chongwumr宠物美容":        "公众服务类",
	"meifadianz美容店长":       "公众服务类",
	"meirongguwen美容/瘦身顾问":  "公众服务类",
	"caizhuangpeixun彩妆培训师": "公众服务类",
	"zpmeitishi美体师":        "公众服务类",

	"zpjiudian旅游":    "公众服务类",
	"zpdingpiao订票员":  "公众服务类",
	"dyao导游":         "公众服务类",
	"zpjidiao计调":     "公众服务类",
	"qianzheng签证专员":  "公众服务类",
	"lvyouguwen旅游顾问": "公众服务类",

	"zpwentiyingshi娱乐/休闲": "公众服务类",
	"jiubagzy酒吧服务员":       "公众服务类",
	"yulefwy娱乐厅服务员":       "公众服务类",
	"wtliyi礼仪/迎宾":         "公众服务类",
	"wtzhuchiren主持人":      "公众服务类",
	"tiaojiushi调酒师":       "公众服务类",
	"wtluying音效师":         "公众服务类",
	"dengguangshi灯光师":     "公众服务类",
	"wtxieying摄影师/摄像师":    "公众服务类",
	"yingshicehua影视/后期制作": "公众服务类",
	"peiyin配音员":           "公众服务类",
	"fangyingyuan放映员":     "公众服务类",

	"zpanmo保健按摩":           "公众服务类",
	"zhenjiuzg按摩师":         "公众服务类",
	"baojiananmozuliao足疗师": "公众服务类",
	"zpcuozao搓澡工":          "公众服务类",
	"zptuina针灸推拿":          "公众服务类",

	"zpjianshen运动健身":       "公众服务类",
	"jianshenguwen健身教练":    "公众服务类",
	"yujiawudaolaoshi瑜伽教练": "公众服务类",
	"zpwudao舞蹈老师":          "公众服务类",
	"zpyouyong游泳教练":        "公众服务类",
	"zptaiqiu台球教练":         "公众服务类",
	"zpgaoerfu高尔夫球助理":      "公众服务类",

	//人力 | 行政 | 管理
	"renli人事/行政/后勤":             "行政/人力资源管理类",
	"wenziluru文员":               "行政/人力资源管理类",
	"qiantai前台/总机/接待":           "行政/人力资源管理类",
	"zhaopinjingli人事专员/助理":      "行政/人力资源管理类",
	"renshizhuguan人事经理/主管":      "行政/人力资源管理类",
	"renshizongjian人事总监":        "行政/人力资源管理类",
	"xingzhengzhuanyuan行政专员/助理": "行政/人力资源管理类",
	"xingzhengjingli行政经理/主管":    "行政/人力资源管理类",
	"xingzhengzongjian行政总监":     "行政/人力资源管理类",
	"mishu经理助理/秘书":              "行政/人力资源管理类",
	"xinzifuli薪酬/绩效/员工关系":       "行政/人力资源管理类",
	"lietouguwen猎头顾问":           "行政/人力资源管理类",
	"houqin后勤":                  "行政/人力资源管理类",
	"peixunzhuanyuan培训专员/助理":    "行政/人力资源管理类",
	"peixunjingli培训经理/主管":       "行政/人力资源管理类",
	"zhaopinzhuanyuan招聘专员/助理":   "行政/人力资源管理类",
	"zhaopinzhuguan招聘经理/主管":     "行政/人力资源管理类",

	"siji司机":                  "技工类",
	"shangwujiaochesiji商务司机":  "技工类",
	"changtukeyuansiji客运司机":   "技工类",
	"sonhuosiji货运司机":          "技工类",
	"chuzuchesiji出租车司机":       "技工类",
	"gongjiaobanchesiji班车司机":  "技工类",
	"tezhongchesiji特种车司机":     "技工类",
	"jiaoxiaojiaolian驾校教练/陪练": "技工类",

	"zpguanli高级管理":           "经营管理类",
	"zpzongcaiCEO/总裁/总经理":    "经营管理类",
	"shouxiyunying首席运营官COO":  "经营管理类",
	"shouxicaiwu首席财务官CFO":    "经营管理类",
	"shouxijishu首席技术官CTO":    "经营管理类",
	"fuzongcai副总裁/副总经理":      "经营管理类",
	"zongcaizhuli总裁助理/总经理助理": "经营管理类",
	"zongjian总监":             "经营管理类",
	"fengongsijingli分公司经理":   "经营管理类",
	"hehuoren合伙人":            "经营管理类",

	//销售 | 客服 | 采购 | 淘宝
	"yewu销售":                   "贸易/销售/业务类",
	"xiaoshouyuan销售代表":         "贸易/销售/业务类",
	"xiaoshouzhuli销售助理":        "贸易/销售/业务类",
	"xiaoshoujingli销售经理/主管":    "贸易/销售/业务类",
	"xiaoshouzongjian销售总监":     "贸易/销售/业务类",
	"dianhuaxiaoshou电话销售":      "贸易/销售/业务类",
	"xiaoshougongchengshi销售支持": "贸易/销售/业务类",
	"qichexiaoshou汽车销售":        "贸易/销售/业务类",
	"yiyaodaibiao医药代表":         "贸易/销售/业务类",
	"yiliaoqixie医疗器械销售":        "贸易/销售/业务类",
	"wangluoxiaoshouyuan网络销售":  "贸易/销售/业务类",
	"quyuxiaoshou区域销售":         "贸易/销售/业务类",
	"qudaorenyuan渠道专员":         "贸易/销售/业务类",
	"qudaojingli渠道经理/总监":       "贸易/销售/业务类",
	"kehujingli客户经理/主管":        "贸易/销售/业务类",
	"dakehujingli大客户经理":        "贸易/销售/业务类",
	"tuangouxiaoshou团购业务员/经理":  "贸易/销售/业务类",
	"huijiguwen会籍顾问":           "贸易/销售/业务类",

	"kefu客服":               "客户服务类",
	"kefuzhuanyuan客服专员/助理": "客户服务类",
	"kefujingli客服经理/主管":    "客户服务类",
	"kefuzongjian客服总监":     "客户服务类",
	"shouhoufuwu售前/售后服务":   "客户服务类",
	"kehuzixun电话客服":        "客户服务类",
	"kehuguanxi客户关系管理":     "客户服务类",

	"zpshangwumaoyi贸易/采购":     "贸易/销售/业务类",
	"waimaozhuanyuan外贸专员/助理":  "贸易/销售/业务类",
	"waimaojingli外贸经理/主管":     "贸易/销售/业务类",
	"caigouyuan采购员":           "贸易/销售/业务类",
	"caigouzhuli采购助理":         "贸易/销售/业务类",
	"caigouguanli采购经理/总监":     "贸易/销售/业务类",
	"danzhengbaoguan报关员":      "贸易/销售/业务类",
	"shangwuzhuanyuan商务专员/经理": "贸易/销售/业务类",
	"maishou买手":               "贸易/销售/业务类",

	"chaoshishangye超市/百货/零售": "贸易/销售/业务类",
	"yingyeyuan店员/营业员":       "贸易/销售/业务类",
	"shouying收银员":            "贸易/销售/业务类",
	"cuxiao促销/导购员":           "贸易/销售/业务类",
	"lihuoyuan理货员/陈列员":       "贸易/销售/业务类",
	"fangsunyuan防损员/内保":      "贸易/销售/业务类",
	"dianzhang店长/卖场经理":       "贸易/销售/业务类",
	"zhaoshangjingli招商经理/主管": "贸易/销售/业务类",
	"shechipinyewu奢侈品业务":     "贸易/销售/业务类",
	"pinleiguanli品类管理":       "贸易/销售/业务类",
	"shipinjiagong食品加工/处理":   "贸易/销售/业务类",
	"zpdudao督导":              "贸易/销售/业务类",

	"zptaobao淘宝职位":          "贸易/销售/业务类",
	"zptaobaodianzhang网店店长": "贸易/销售/业务类",
	"zptaobaokefu淘宝客服":      "贸易/销售/业务类",
	"zptaobaomeigong淘宝美工":   "贸易/销售/业务类",
	"zptaobaobianji店铺文案编辑":  "贸易/销售/业务类",
	"zptaobaotuiguang店铺推广":  "贸易/销售/业务类",
	"zptaobaocehua活动策划":     "贸易/销售/业务类",

	"zpfangchan房产中介":             "贸易/销售/业务类",
	"fangdichan房产经纪人":            "贸易/销售/业务类",
	"zpzhiye置业顾问":                "贸易/销售/业务类",
	"zpfangchandianzhang房产店长/经理": "贸易/销售/业务类",
	"zpfangchandianyuan房产店员/助理":  "贸易/销售/业务类",
	"zpfangchankefu房产客服":         "贸易/销售/业务类",
	"zpfangchanneiqin房产内勤":       "贸易/销售/业务类",
	"zpfangchanpinggu房产评估师":      "贸易/销售/业务类",
	"fangdichankaifa房产开发/策划":     "贸易/销售/业务类",
	"zpfangchanqita其他房产职位":       "贸易/销售/业务类",

	// 酒店
	"jiudianzp酒店":  "酒店/餐饮类",
	"loucjl楼层经理":   "酒店/餐饮类",
	"xiyifjl洗衣房经理": "酒店/餐饮类",
	"ggqyjl公共区域经理": "酒店/餐饮类",
	"keffwy客房服务员":  "酒店/餐饮类",
	"fwbzj房务部总监":   "酒店/餐饮类",
	"kfbjl客房部经理":   "酒店/餐饮类",
	"ydjl预订经理":     "酒店/餐饮类",
	"yudingy预订员":   "酒店/餐饮类",
	"zjjl总机经理":     "酒店/餐饮类",
	"zjyg总机员工":     "酒店/餐饮类",
	"qtbjl前厅部经理":   "酒店/餐饮类",
	"qtzg前台主管":     "酒店/餐饮类",
	"lbjl礼宾经理":     "酒店/餐饮类",
	"bkgxzr宾客关系主任": "酒店/餐饮类",
	"qtbyg前厅部员工":   "酒店/餐饮类",
	"dtfl大堂副理":     "酒店/餐饮类",
	"zbjl值班经理":     "酒店/餐饮类",
	"qtjd前台/接待":    "酒店/餐饮类",
	"jiusy救生员":     "酒店/餐饮类",
	"zongjl总经理":    "酒店/餐饮类",
	"zjlzl总经理助理":   "酒店/餐饮类",
	"jddzh酒店店长":    "酒店/餐饮类",

	//市场 | 媒介 | 广告 | 设计
	"shichang市场/媒介/公关":                   "公关/市场营销类",
	"yingxiaozhuanyuan市场专员/助理":           "公关/市场营销类",
	"shichangzongjian市场经理/总监":            "公关/市场营销类",
	"shichangzhuanyuan市场拓展":              "公关/市场营销类",
	"shichangdiaoyan市场调研":                "公关/市场营销类",
	"qihua市场策划":                          "公关/市场营销类",
	"shichangcehuagongguanmeijie媒介专员/助理": "公关/市场营销类",
	"meijiejingli媒介经理/主管":                "公关/市场营销类",
	"huiwujingli会务会展专员/经理":               "公关/市场营销类",
	"pinpaijingli品牌专员/经理":                "公关/市场营销类",
	"gongguanzhuanyuan公关专员/助理":           "公关/市场营销类",
	"gongguanjingli公关经理/主管":              "公关/市场营销类",
	"qihuajingli企划经理/主管":                 "公关/市场营销类",

	"zpguanggao广告/会展/咨询":      "其他专业类",
	"wenan广告文案":               "其他专业类",
	"chuangyizongjian创意指导/总监": "其他专业类",
	"fengmiansj广告设计/制作":       "其他专业类",
	"shejichuangyi广告创意":       "其他专业类",
	"zpmeijiecehua媒介策划/管理":    "其他专业类",
	"huizhancehua会展策划/设计":     "其他专业类",
	"zphunlicehua婚礼策划师":       "其他专业类",
	"zixunshi咨询顾问":            "其他专业类",
	"zixunjingli咨询经理/主管":      "其他专业类",
	"zpkehuzhuguan客户主管/专员":    "其他专业类",
	"zpqiyecehua企业策划":         "其他专业类",

	"zpmeishu美术/设计/创意":             "设计类",
	"meibian美编/美术设计":               "设计类",
	"fuzhuangsj服装设计":               "设计类",
	"jiajusj家具/家居用品设计":             "设计类",
	"sheji平面设计":                    "设计类",
	"meishuzhidao美术指导":             "设计类",
	"zhanshizhuanghuang店面/陈列/展览设计": "设计类",
	"gongyisheji工艺/珠宝设计":           "设计类",
	"duomeiti多媒体/动画设计":             "设计类",
	"baozhuangsheji产品/包装设计":        "设计类",
	"shineisheji装修装潢设计":            "设计类",
	"shejizhituCAD设计/制图":           "设计类",

	//生产 | 物流 | 质控 | 汽车
	"zpshengchankaifa普工/技工":   "技工类",
	"pugong普工":                "技工类",
	"weixiugongchengshi综合维修工": "技工类",
	"nuantonggong制冷/水暖工":      "技工类",
	"dianzi电工":                "技工类",
	"mugong木工":                "技工类",
	"qiangong钳工":              "技工类",
	"maohangong切割/焊工":         "技工类",
	"banjin钣金工":               "技工类",
	"youqigong油漆工":            "技工类",
	"fengrengong缝纫工":          "技工类",
	"gulugong锅炉工":             "技工类",
	"shukongjichuang车工/铣工":    "技工类",
	"chachegong铲车/叉车工":        "技工类",
	"mojugong铸造/注塑/模具工":       "技工类",
	"ditigong电梯工":             "技工类",
	"zhizaogongchengshi操作工":   "技工类",
	"baozhuanggcs包装工":         "技工类",
	"shoujiwx手机维修":            "技工类",
	"zpshuini水泥工":             "技工类",
	"zpgangjin钢筋工":            "技工类",
	"zpguangdao管道工":           "技工类",
	"zpwagong瓦工":              "技工类",
	"zpzuzhuang组装工":           "技工类",
	"zpyangyigong样衣工":         "技工类",
	"zprangong染工":             "技工类",
	"zpfangzhi纺织工":            "技工类",
	"zpyinhua印花工":             "技工类",
	"zpyayun压熨工":              "技工类",

	"zpshengchan生产管理/研发":         "工厂类",
	"zhiliangbaozhengqa质量管理":     "工厂类",
	"zonggongchengshi总工程师/副总工程师": "工厂类",
	"gcsbguanli设备管理维护":           "工厂类",
	"jsgysheji工艺设计":              "工厂类",
	"shengchanjingli车间主任":        "工厂类",
	"jihuatiaodu生产计划":            "工厂类",
	"huayan化验/检验":                "工厂类",
	"changzhang厂长/副厂长":           "工厂类",
	"shengchanzongjian生产总监":      "工厂类",
	"weixiugong维修工程师":            "工厂类",
	"gongyegcs工业工程师":             "工厂类",
	"cailiaogcs材料工程师":            "工厂类",
	"jishugongcheng技术工程师":        "工厂类",
	"shengchanzhuguan生产主管/组长":    "工厂类",

	"zpwuliucangchu物流/仓储":     "物流/交通运输类",
	"maoyi物流专员/助理":            "物流/交通运输类",
	"wuliujingli物流经理/主管":      "物流/交通运输类",
	"wuliuzongjian物流总监":       "物流/交通运输类",
	"diaodu调度员":               "物流/交通运输类",
	"sudiyuan快递员":             "物流/交通运输类",
	"cangku仓库管理员":             "物流/交通运输类",
	"cangkujingli仓库经理/主管":     "物流/交通运输类",
	"banyungong装卸/搬运工":        "物流/交通运输类",
	"gongyinglianguanli供应链管理": "物流/交通运输类",
	"danzhengyuan单证员":         "物流/交通运输类",
	"guojihuoyun国际货运":         "物流/交通运输类",

	"xiaofeipin服装/纺织/食品":    "其他专业类",
	"fuzhuangsheji服装设计师":    "设计类",
	"fangzhisheji纺织品设计师":    "设计类",
	"fuzhuangdayang服装打样/制版": "其他专业类",
	"shengchanguanli生产管理":   "其他专业类",
	"yangyigong样衣工":         "其他专业类",
	"shipinyanfa食品/饮料研发/检验": "其他专业类",
	"chugeshi板房/底格出格师":      "其他专业类",
	"fangmayuan电脑放码员":       "其他专业类",
	"zhiyangshi纸样师/车板工":     "其他专业类",

	"zhikonganfang质控/安防":      "其他专业类",
	"zhiliangguanli质量管理/测试经理": "其他专业类",
	"zhijianyuan质量检验员/测试员":    "其他专业类",
	"ceshigongchengshi测试工程师":  "其他专业类",
	"anquanxiaofang安全消防":      "其他专业类",
	"renzhengyuan认证工程师/审核员":   "其他专业类",
	"anquanguanli安全管理":        "其他专业类",

	"zpqiche汽车制造/服务":          "其他专业类",
	"qichesheji汽车设计工程师":       "其他专业类",
	"zhuangpeigongyi装配工艺工程师":  "其他专业类",
	"qichewx汽车/摩托车修理":         "公众服务类",
	"qichejixie汽车机械工程师":       "其他专业类",
	"qichedianzi汽车电子工程师":      "其他专业类",
	"qcfsweixiu4S店管理":         "其他专业类",
	"jianyanjiance汽车检验/检测":    "公众服务类",
	"qichemeirong汽车美容":        "公众服务类",
	"qcpinggushi二手车评估师":       "其他专业类",
	"qczozhuang发动机/总装工程师":     "其他专业类",
	"qcanquanxingneng安全性能工程师": "其他专业类",
	"qclipei理赔专员/顾问":          "公众服务类",
	"xicheyuan洗车工":            "公众服务类",
	"tingcheguanli停车管理员":      "公众服务类",
	"jiayougong加油站工作员":        "公众服务类",
	"luntaigong轮胎工":           "公众服务类",

	//网络 | 通信 | 电子
	"tech计算机/互联网/通信":           "计算机/互联网类",
	"jishuzongjian技术总监/经理":     "计算机/互联网类",
	"jishuzhichi技术支持/维护":       "计算机/互联网类",
	"jszhuanyuan技术专员/助理":       "计算机/互联网类",
	"ruanjiangong软件工程师":        "计算机/互联网类",
	"chengxuyuan程序员":           "计算机/互联网类",
	"yingjiangong硬件工程师":        "计算机/互联网类",
	"zhilianggongcheng质量工程师":   "计算机/互联网类",
	"yingjiancs测试工程师":          "计算机/互联网类",
	"xitongjichengfenxi系统架构师":  "计算机/互联网类",
	"shujukukaifa数据库管理/DBA":    "计算机/互联网类",
	"youxisheji游戏设计/开发":        "计算机/互联网类",
	"wangzhanmeigong网页设计/制作":   "计算机/互联网类",
	"cadsheji语音/视频/图形":         "计算机/互联网类",
	"xiangmuzongjian项目经理/主管":   "计算机/互联网类",
	"wangzhanchanpin产品经理/专员":   "计算机/互联网类",
	"wangzhanyunying网站运营":      "计算机/互联网类",
	"wangzhanyingyun网站编辑":      "计算机/互联网类",
	"wangzhancehua网站策划":        "计算机/互联网类",
	"wangluogongchengshi网络管理员": "计算机/互联网类",
	"wangluoanquan网络与信息安全工程师":  "计算机/互联网类",
	"ruanjianshishi实施工程师":      "计算机/互联网类",
	"tongxinwuxian通信技术工程师":     "计算机/互联网类",

	"zpjixieyiqi电子/电气":              "电子/通讯类",
	"zidonghua自动化工程师":               "电子/通讯类",
	"dianzidianqigcs电子/电气工程师":       "电子/通讯类",
	"didianqigongchengshi电路工程师/技术员": "电子/通讯类",
	"wuxiandiangcs无线电工程师":           "电子/通讯类",
	"ceshigcs测试/可靠性工程师":             "电子/通讯类",
	"gongyigcs产品工艺/规划工程师":           "电子/通讯类",
	"yinpinshipingcs音频/视频工程师":       "电子/通讯类",
	"zhaomingsheji灯光/照明设计工程师":       "电子/通讯类",
	"yanfagcs研发工程师":                 "电子/通讯类",
	"dianzidianqiwx电子/电器维修":         "电子/通讯类",

	"zpjixie机械/仪器仪表":           "机械类",
	"jxjixiegongchengshi机电工程师": "机械类",
	"zpjixiegongcheng机械工程师":    "机械类",
	"zpyanfa研发工程师":             "机械类",
	"zpceshi测试/可靠性工程师":         "机械类",
	"bantushejigcs版图设计工程师":     "机械类",
	"jxyiqigongcheng仪器/仪表/计量":  "机械类",

	//法律 | 教育 | 翻译 | 出版
	"zpfalvzixun法律":       "法律类",
	"lvshizhaopin律师/法律顾问": "法律类",
	"lvshizhuli律师助理":      "法律类",
	"lfawurenyuan法务专员/主管": "法律类",
	"zhuanliguwen产权/专利顾问": "法律类",
	"heguiguanli合规管理":     "法律类",

	"zhuanye教育培训":            "文化/教育/体育/艺术类",
	"jiaoshi教师/助教":           "文化/教育/体育/艺术类",
	"jiajiaolaoshi家教":        "文化/教育/体育/艺术类",
	"youerjiaoshi幼教/早教":      "文化/教育/体育/艺术类",
	"jypeixunshi培训师/讲师":      "文化/教育/体育/艺术类",
	"peixuncehua培训策划":        "文化/教育/体育/艺术类",
	"peixunzhuli培训助理":        "文化/教育/体育/艺术类",
	"jiaowu教学/教务管理":          "文化/教育/体育/艺术类",
	"jiaoyukaifa教育产品开发":      "文化/教育/体育/艺术类",
	"jykeyuanrenyuan学术研究/科研": "文化/教育/体育/艺术类",
	"jyzhaosheng招生/课程顾问":     "文化/教育/体育/艺术类",
	"xiaozhang校长":            "文化/教育/体育/艺术类",
	"tuozhanshi野外拓展训练师":      "文化/教育/体育/艺术类",

	"fanyizhaopin翻译":          "文职类",
	"yingyufanyi英语翻译":         "文职类",
	"riyufanyi日语翻译":           "文职类",
	"hanyu韩语翻译":               "文职类",
	"fayufanyi法语翻译":           "文职类",
	"eyufanyi俄语翻译":            "文职类",
	"deyufanyi德语翻译":           "文职类",
	"xibanyayu西班牙语翻译":         "文职类",
	"yidaliyu意大利语翻译":          "文职类",
	"putaoyayu葡萄牙语翻译":         "文职类",
	"alaboyu阿拉伯语翻译":           "文职类",
	"jyxiaoyuzhongfanyi小语种翻译": "文职类",

	"zpxiezuochuban编辑/出版/印刷": "文职类",
	"cbzhubian总编/副总编/主编":     "文职类",
	"bianji编辑/撰稿":            "文职类",
	"jizhe记者/采编":             "文职类",
	"cbchuban出版/发行":          "文职类",
	"cbyishua排版设计/制作":        "文职类",
	"cbyinshuacaozuo印刷操作":    "文职类",
	"zhuangdingyuan装订/烫金":    "文职类",

	//财会 | 金融 | 保险
	"zpcaiwushenji财务/审计/统计":  "财务类",
	"caiwujingli财务经理/主管":     "财务类",
	"caiwuzongjian财务总监":      "财务类",
	"caiwu会计/会计师":            "财务类",
	"caiwuzhuli财务/会计助理":      "财务类",
	"chuna出纳":                "财务类",
	"tongjishenji审计专员/助理":    "财务类",
	"shenjijingli审计经理/主管":    "财务类",
	"tongjiyuan统计员":          "财务类",
	"shuiwuzhuanyuan税务专员/助理": "财务类",
	"shuiwujingli税务经理/主管":    "财务类",
	"caiwufenxi财务分析员":        "财务类",
	"zpchengben成本管理员":        "财务类",

	"jinrongtouzi金融/银行/证券/投资": "金融/经济",
	"jingjiren证券/期货/外汇经纪人":    "金融/经济",
	"zhengquanjingli证券经理/总监":  "金融/经济",
	"zhengquanfenxi证券分析/金融研究": "金融/经济",
	"yinhangyewu信用卡/银行卡业务":    "金融/经济",
	"yinhangjingli银行经理/主任":    "金融/经济",
	"yinhangkuaiji银行会计/柜员":    "金融/经济",
	"zichanpinggu信贷管理/资信评估":   "金融/经济",
	"zcpinggu资产评估":            "金融/经济",
	"danbaopaimai担保/拍卖/典当":    "金融/经济",
	"paimaishi拍卖师":            "金融/经济",
	"waihuijingli外汇/基金/国债经理人": "金融/经济",
	"jinrong投资/理财顾问":          "金融/经济",
	"rongzizhuanyuan融资专员":     "金融/经济",
	"rongzijingli融资经理/总监":     "金融/经济",
	"fengxiankongzhi风险管理/控制":  "金融/经济",
	"caopanshou股票交易员":         "金融/经济",

	"zpjinrongbaoxian保险":    "金融/经济",
	"chubeijingli储备经理人":     "金融/经济",
	"baoxianjchanpin保险客户经理": "金融/经济",
	"baoxianlipei车险专员":      "金融/经济",
	"baoxianneiqin保险内勤":     "金融/经济",
	"baoxianpeixun保险培训师":    "金融/经济",
	"baoxianxuqi保险客服":       "金融/经济",
	"baoxianguwen保险顾问":      "金融/经济",
	"baoxian保险经纪人":          "金融/经济",
	"baoxianjingli保险项目经理":   "金融/经济",
	"baoxianjingsuan保险精算师":  "金融/经济",
	"qiyueguanli保险其他职位":     "金融/经济",

	// 医疗 | 制药 | 环保
	"zpyiyuanyiliao医院/医疗/护理":  "医疗卫生/护理/保健类",
	"yiliao医生":                "医疗卫生/护理/保健类",
	"baojianyisheng保健医生":      "医疗卫生/护理/保健类",
	"yyxinliyisheng心理医生":      "医疗卫生/护理/保健类",
	"hushi护士/护理":              "医疗卫生/护理/保健类",
	"hushizhang护理主任/护士长":      "医疗卫生/护理/保健类",
	"daoyiyuan导医":             "医疗卫生/护理/保健类",
	"yyyaokuzhuren药剂师":        "医疗卫生/护理/保健类",
	"yyliliaoshi理疗师":          "医疗卫生/护理/保健类",
	"yyyiyaoxuejianyan医药质检":   "医疗卫生/护理/保健类",
	"yyyiyuan医疗管理":            "医疗卫生/护理/保健类",
	"yymeirongzhengxing美容整形师": "医疗卫生/护理/保健类",
	"yanguangshi验光师":          "医疗卫生/护理/保健类",
	"yyyingyangshi营养师":        "医疗卫生/护理/保健类",
	"chongwuyisheng宠物护理/兽医":   "医疗卫生/护理/保健类",

	"zpzhiyao制药/生物工程":           "医疗卫生/护理/保健类",
	"yiyaoyanfa医药研发/生产/注册":      "医疗卫生/护理/保健类",
	"linchuangyanjiu临床研究/协调":    "医疗卫生/护理/保健类",
	"shengwugongcheng生物工程/生物制药": "医疗卫生/护理/保健类",
	"yiliaoyanfa医疗器械研发/维修":      "医疗卫生/护理/保健类",

	"huanbao环保":              "其他专业类",
	"wushuichuli污水处理工程师":     "其他专业类",
	"hjgongchengjishu环境工程技术": "其他专业类",
	"hjguanli环境管理/保护":        "其他专业类",
	"huanbaojishu环保技术":       "其他专业类",
	"ehsguanliEHS管理":         "其他专业类",
	"huanbaoshi环保工程师":        "其他专业类",
	"huanbaojiance环保检测":      "其他专业类",
	"shuizhijiance水质检测员":     "其他专业类",
	"hjlvhua环境绿化":            "其他专业类",

	//建筑 | 装修 | 物业 | 其他
	"zpfangchanjianzhu建筑":         "规划/建筑/建材类",
	"jianzhugongcheng工程项目管理":      "规划/建筑/建材类",
	"gongchengjianli工程监理":         "规划/建筑/建材类",
	"jianzhugongchengshi建筑工程师/总工": "规划/建筑/建材类",
	"jiegoutumu土木/土建工程师":          "规划/建筑/建材类",
	"gongchengzhaojia造价师/预算师":     "规划/建筑/建材类",
	"muqiang幕墙工程师":                "规划/建筑/建材类",
	"jianzhuanfang安防工程师":          "规划/建筑/建材类",
	"jzanquanguanli安全管理/安全员":      "规划/建筑/建材类",
	"gongluqiaoliang道路桥梁技术":       "规划/建筑/建材类",
	"geipaishui给排水/制冷/暖通":         "规划/建筑/建材类",
	"cehuiceliang测绘/测量":           "规划/建筑/建材类",
	"fangwusj园林/景观设计":             "规划/建筑/建材类",
	"ziliao资料员":                   "规划/建筑/建材类",
	"shizhenggc市政工程师":             "规划/建筑/建材类",
	"buxianruodian综合布线/弱电":        "规划/建筑/建材类",

	"zpwuye物业管理":               "房地产/物业管理类",
	"wuye物业管理员":                "房地产/物业管理类",
	"zonghewuyeweixiugong物业维修": "房地产/物业管理类",
	"wuyejingli物业经理/主管":        "房地产/物业管理类",
	"jzhetong合同管理":             "房地产/物业管理类",
	"fczhaoshang招商经理/主管":       "房地产/物业管理类",

	"nonglinmuyu农/林/牧/渔业":  "其他专业类",
	"siliao饲料业务":           "其他专业类",
	"yangzhi养殖人员":          "其他专业类",
	"nongyishi农艺师/花艺师":     "其他专业类",
	"xumushi畜牧师":           "其他专业类",
	"nongchangzhu场长":       "其他专业类",
	"yangzhizhuguan养殖部主管":  "其他专业类",
	"siliaoyanfa动物营养/饲料研发": "其他专业类",

	"zhaopin其他招聘信息":    "其他专业类",
	"cgqitazhiwei其他职位": "其他专业类",

	"zhaopinhui招聘会":         "其他专业类",
	"zhuanchang专场招聘会":       "其他专业类",
	"zphyingjiesheng应届生招聘会": "其他专业类",
	"zphzonghe综合招聘会":        "其他专业类",
	"zphgaoji中高级人才招聘会":      "其他专业类",
}

// EducationMate 学历分类匹配关系
var EducationMate = map[string]string{
	"高中": "高中",
	"技校": "技校",
	"中专": "中专",
	"大专": "大专",
	"本科": "本科",
	"硕士": "硕士",
	"博士": "博士",
}

// ExperienceMate 工作经验匹配关系
var ExperienceMate = map[string]string{
	"1年以下":  "1年以下",
	"1-2年":  "1-2年",
	"3-5年":  "3-5年",
	"6-7年":  "6-7年",
	"8-10年": "8-10年",
	"10年以上": "10年以上",
}

// WelfareMate 标签匹配关系
var WelfareMate = map[string]string{
	"五险一金": "五险一金",
	"包住":   "包住",
	"包吃":   "包吃",
	"年底双薪": "年底双薪",
	"周末双休": "周末双休",
	"交通补助": "交通补助",
	"加班补助": "加班补助",
	"饭补":   "饭补",
	"话补":   "话补",
	"房补":   "房补",
}
